services:
  db:
    image: mysql:8.0
    container_name: sp_db
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
    ports:
      - "${DB_PORT}:3306"